### ISSUE TITLE
[FEATURE] Add an inspector context to the editor

### ISSUE THREAD

**Issue by AdamRamberg** [unity-atoms/unity-atoms#107]
**Is your feature request related to a problem? Please describe.**
The UX / DX for working with multiple assets is sometimes frustrating and clunky. This issues addresses the problem of going between atoms in the Unity editor. 

**Describe the solution you'd like**
I want to add an inspector context for atoms. This means that if you have an atom in a list, like the pre change transformers, you can click on "go to atom". When you are viewing the inspector for that Atom you will have a back button getting you back to the last Atom shown in the inspector. This would enable a much smoother workflow working with something like the pre change transformers.

**Describe alternatives you've considered**
Use the vanilla editor. 

**Additional context**
This change was discussed and proposed in PR #93.

**Comment by soraphis** [comment]
not sure if we want to keep this in our backlog.
especially with the "have a back button"...

in the meantime using https://openupm.com/packages/com.bedtime.editor-history/ already gives you the option to use the back button of the mouse to get back and a double click on an atom in the inspector brings you to the atom.

**Comment by AdamRamberg** [comment]
I agree. Closing this issue.
