### ISSUE TITLE
[QUESTION] Is it intentional that AtomBaseVariable uses `Reset` method with a paramter?

### ISSUE THREAD

**Issue by mnarimani** [unity-atoms/unity-atoms#148]
`Reset` method is an Unity event function that will be called when you create a component and when you use the Reset option in the context menu.
But AtomBaseVariable defines wrong signature of this method. 
https://github.com/AdamRamberg/unity-atoms/blob/ce9e818ac3d9315364ebf539926597a77a5adb85/Packages/Core/Runtime/Variables/AtomBaseVariable.cs#L26
This is confusing. Specially with the optional parameter that turns the invocations of this method into the original Unity event function signature.

Unity event function:
https://docs.unity3d.com/2020.1/Documentation/ScriptReference/ScriptableObject.Reset.html

**Comment by soraphis** [comment]
yes you're right it is confusing. whats even more confusing is, that its overriden with throwing an exception:

https://github.com/AdamRamberg/unity-atoms/blob/e2bc533807c3b47b0bae2123bed85c0e0900611f/Packages/Core/Runtime/Variables/AtomBaseVariable.cs#L74-L77

but this shows, that the method is not called by Unity's underlying system. (or the exception would be thrown)

Adding this methods, to a generated Variable code:

```
        public override void Reset(bool shouldTriggerEvents = false)
        {
            base.Reset(shouldTriggerEvents);
            Debug.Log("Resetting!");
        }

        public void Reset()
        {
            Debug.Log("Unity Event Reset");
        }
```

- it compiles just fine
- when creating an asset it logs: "Unity Event Reset"
- to call the overriden method you can use `(this as AtomBaseVariable).Reset();`

so, there is not that much ambiguity as one would think.

The reset method is used in a few places (FSM and VariableResetter) but I think there is a bit of potential to make it less confusing

**Comment by AdamRamberg** [comment]
Thanks for reporting this issue! This is not intentional and something that we should address. I believe that what @soraphis suggests is a nice addition to v4 of Unity Atoms to make it less confusing. In v5 I believe we should rename the method to something like `ResetValue` or `ResetAtom`. What are your opinions on this @soraphis / @mnarimani?

**Comment by mnarimani** [comment]
@AdamRamberg I think `ResetValue` will certainly be a better name. I think `ResetAtom` does not explain what is going to be reset. (Any atom has multiple fields. Id, Description, Events,...)
@soraphis I think you're right. But part of my confusion was because I thought it was a crazy hack to actually use Unity event callback function to reset some values. That's why I asked if it was intentional or not.

**Comment by miikalo** [comment]
Thanks, the question was converted into an issue, please see #249.
