### ISSUE TITLE
[FEATURE] Better Bolt intergration

### ISSUE THREAD

**Issue by bguyl** [unity-atoms/unity-atoms#183]
**Is your feature request related to a problem? Please describe.**
While it's not so difficult to make Bolt and Atoms work together, certain things seems a little bit off.

Few examples:

- You can't make an _Atom Reference_ node, you can only make an _Atom Constant_ or an _Atom Variable_ node. Nor have a _Atom Reference_ as a _Bolt Variable_

- _Atom Events_ can't be directly listened in a graph. You have several ways to achieve this, like add to your GameObject an _EventListener_ which will trigger an _UnityEvent_ which will call an _UnityEvent_ node on the chart. It is not the most user friendly

- There are no icons on nodes

![image](https://user-images.githubusercontent.com/24865257/88461524-8506df80-cea4-11ea-89ad-f9de977ce989.png)

**Describe the solution you'd like**
It might be a good idea to have an other Atoms module for a natural Bolt integration, as I thing the two plugin try to achieve a similar goal (give better tools to game designers) and could work perfectly together.

**Additional context**
In may 2020 Unity acquired Bolt and stated they are working on a V2 and since july they release it for free for everyone.
It's clear that Bolt will be an important part of Unity workflow as a direct competitor of UE blueprint.

**Comment by AdamRamberg** [comment]
Hi @bguyl! Sounds definitely like a nice thing to add to Atoms! Not sure if I will have the time to do this myself, but if you or someone else is up for a PR is most welcomed.

**Comment by TowerCrow** [comment]
The current Bolt API is sparsely documented (read, not documented at all officially). There are some community tutorials and user made extensions and asset's source that can be studied but it's not a lot to go on.

Unity plan to implement a new, parallel API for custom node coding which will be documented and easier to work with once it's ready. So it might be worth waiting until that's done.

**Comment by bguyl** [comment]
I started working on this topic in a separate package: https://github.com/bguyl/unity-atoms-vs

**Comment by miikalo** [comment]
Added this to Backlog milestone as v4 won't have new features and it's uncertain if this will be in v5.

**Comment by soraphis** [comment]
I'll close this since 
a) bguyl has created an own repo for this as an addon - which is perfectly fine to do. 
b) there is no much traction on this issue (january 2021)
c) it currently does not look like one of us maintainers will work on it.
