### ISSUE TITLE
[FEATURE] Create button improvements

### ISSUE THREAD

**Issue by TowerCrow** [unity-atoms/unity-atoms#198]
**Is your feature request related to a problem? Please describe.**

I'm working on adventure-like Hotspot scripting and I'm in the process of automatizing the creation of Atom events, hotspot conditions (BoolVariables) and other atom related assets. Each hotspot has unique atom events and atom bool conditions so I place them in Hotspot relevant folders. Something like Assets/_GAME_/HotspotData/ActiveScene/HotspotName. 

The built in Create button, while convenient for creating new assets, is not working for us since it doesn't respect our project structure. It dumps everything in the root folder Assets. So I made my own buttons that creates atom events and atom variables, apply them in the Hotspot script and places them in folders appropriate for our project structure. This works well, except now I have my own Hotspot script Create buttons and Atoms Create buttons coexisting, which makes it confusing for designers.

**Describe the solution you'd like**

An option for globally disabling Atoms Create button for variables, events, etc.

**Describe alternatives you've considered**

 Offer deeper Atoms Create button settings:
1. A global option to change asset path's root folder from Assets to something like, for example, "Assets/GAME/GameData" .
2. Optional: Let us type in not only asset name but also asset path as one of the new asset creation steps. This could build on suggestion 1 above, so when you need to type in the custom path, it already has added the new root folder path.
3. Option to add path modifiers that build upon suggestion 1's root path. I'm not sure how this could be realized but functionally I'd like to grab things like currently active scene, or GameObject's name the atom event/variable is currently on and where the Create button was pressed. So it would end up being something like "Assets/GAME/GameData/ActiveScene/GameObjectName". Ideally, these could be custom coded per project basis.
4. Let us modify Create button's path via code. Perhaps as an Attribute on top of the variable/event. Or even better - don't show Create button unless it's specifically added via the attribute [CreateButton("Assets/GAME/GameData/" + activeScene + gameObject.name)].

**Comment by miikalo** [comment]
Added this to Backlog because it's uncertain if it's going to be in v5.

**Comment by Casey-Hofland** [comment]
This has been added in V5 (currently in development) using [EditorUtility.SaveFilePanelInProject](https://docs.unity3d.com/ScriptReference/EditorUtility.SaveFilePanelInProject.html) which allows the user to specify a folder location easily and flexibly. To that end, I am closing this issue.

**Comment by Casey-Hofland** [comment]
See [this comment](https://github.com/unity-atoms/unity-atoms/pull/229#issuecomment-758304469) for a short preview of what to expect.
