### ISSUE TITLE
[BUG] Dynamic Assemblies like URP make asset based generator to throw exceptions [BUG]

### ISSUE THREAD

**Issue by soraphis** [unity-atoms/unity-atoms#231]
**Describe the bug**
When the Asset based generator's type dropdown makes an lookup for serialized types it throws exceptions on dynamic assemblies. the URP assembly seems to be dynamic

**To Reproduce**
add Univseral RP via package manage, try to select a type in the asset based generator

**Comment by miikalo** [comment]
Fixed on canary.
