### ISSUE TITLE
FSM is string based, how is performance?

### ISSUE THREAD

**Issue by laurentopia** [unity-atoms/unity-atoms#239]

**Comment by soraphis** [comment]
what part of "performance" is your concern?
transition between states? string comparisons? memory allocation? total memory usage? runtime speed? garbage/heap allocations?

**Comment by miikalo** [comment]
Hi @laurentopia , please use the template for questions. I have pasted it here below:

**State your question below**
State your question. Try to be as precise and detailed as possible. 

**Add any additional information / background**
Add some additional information that might help us understand you question better.

**Comment by miikalo** [comment]
No further info added, closing the question.
