### ISSUE TITLE
[QUESTION] 2 classes named GameObjectGameObjectFunction is proposital?

### ISSUE THREAD

**Issue by niscolas** [unity-atoms/unity-atoms#247]
**State your question below**
I was using the "OnTriggerHook" with the "GameObjectGameObjectFunction" to select the parent of the GameObject and noticed that there are 2 classes that share the same name (GameObjectGameObjectFunction).

One in the MonoHooks package and another in the BaseAtoms, both inherit from AtomFunction<GameObject, GameObject> (this one has only one definition).

Is it proposital?

**Comment by miikalo** [comment]
Hi @niscolas , looks like you found an bug, good catch! Since MonoHooks package depends on BaseAtoms, there's no need for two identical definitions.

**Comment by miikalo** [comment]
I created a bug report (#252) out of this question. Thanks for reporting!

**Comment by niscolas** [comment]
Hey! That's nice, always happy to help :)
