### ISSUE TITLE
[BUG] Condition serialization doesn't work

### ISSUE THREAD

**Issue by ghost** [unity-atoms/unity-atoms#253]
**Describe the bug**
Conditions of reference listeners doesn't show on editor as it is a generic list.

**To Reproduce**
1. Go to 'Any game object'
2. Add 'Any reference listener component'
3. See error: Conditions will not appear

**Expected behavior**
Should able to see conditions on editor.

**Screenshots**

**Environment**
 - OS: Any
 - Unity Version 2019.4
 - Version of Unity Atoms 4.4.2

**Additional context**
It could be working on 2020.1 versions as it support serialization of generics.

**Comment by ThimoVBE** [comment]
I think this could be fixed by adding UNITY_2020_1_OR_NEWER pre processor in the condition code.

**Comment by ThimoDEV** [comment]
I think this could be fixed by adding UNITY_2020_1_OR_NEWER pre processor in the condition code.

**Comment by miikalo** [comment]
I can confirm this, must have been using a newer version of Unity by accident!
