### ISSUE TITLE
[FEATURE]:  Support the reassignment of EventReference in `EventListener`

### ISSUE THREAD

**Issue by yitaya1** [unity-atoms/unity-atoms#273]
**Is your feature request related to a problem? Please describe.**
The problem I have is:
I need to connect a global `EventInstancer`(which exists before the scene plays) to an instantiated `EventListener`.

**Describe the solution you'd like**
As a solution: it'd be helpful if EventReference fields were not locked after initial assignment.

**Describe alternatives you've considered**
I've considered the following alternatives:
1) Transforming the global `EventInstancer` into a `ScriptableObject` 

**Additional context**
A bit out of topic, though it'd be helpful to include more documentation on events usage and best practices.

Thanks in advance

**Comment by miikalo** [comment]
Hi @yitaya1, if the event instancer exists before the scene plays, why not create an Atom Event asset and assign it to scripts? Why does it need to be an event instancer?

**Comment by ThimoDEV** [comment]
I saw this code suggestion @yitaya1 and was wondering if its still something you want to see implemented. Or did @miikalo 's suggestion fix your issue? Was it solved in the Discord perhaps?

**Comment by soraphis** [comment]
Closed as a stale issue, since there are discussion points open. feel free to reopen if necessary
