### ISSUE TITLE
[BUG] [V5] Missmaching field name in editor script for AtomVariable

### ISSUE THREAD

**Issue by bguyl** [unity-atoms/unity-atoms#290]
**Describe the bug**

In AtomVariable, *at least* two fields have change their name

* `_changed` is now `Changed`
* `_changedWithHistory` is now `ChangedWithHistory`

This cause null ref exceptions when trying to display the inspector of a variable

```csharp
        // AtomVariable.cs

        // ...
        /// <summary>
        /// Changed Event triggered when the Variable value gets changed.
        /// </summary>
        public AtomEvent<T> Changed;

        /// <summary>
        /// Changed with history Event triggered when the Variable value gets changed.
        /// </summary>
        public AtomEvent<Pair<T>> ChangedWithHistory;
        // ...
```

```csharp
                // AtomVariableEditor.cs

                // ...
                EditorGUILayout.PropertyField(serializedObject.FindProperty("_changed"));
                var changed = serializedObject.FindProperty("_changed").objectReferenceValue;
                // ...
                EditorGUILayout.PropertyField(serializedObject.FindProperty("_changedWithHistory"));
                var changedWithHistory = serializedObject.FindProperty("_changedWithHistory").objectReferenceValue;
                // ...
```

**Expected behavior**
The solution could be to keep the underscore notation and to add public properties

**Environment**
 - OS: [Windows10]
 - Unity Version: [2020.3.0]
 - Version of Unity Atoms: v5

**Comment by bguyl** [comment]
The issue here is not that API has change for the user, but rather that the API change is not reflected to the editor script

(And in my opinion, as much as I understand the need of making breaking changes, you should keep backward compatibility when it’s free)

**Comment by soraphis** [comment]
Closed as the state of V5 is debatable in general.
