### ISSUE TITLE
[QUESTION] Change private to protected in 'list' variable in AtomValueList

### ISSUE THREAD

**Issue by IceTrooper** [unity-atoms/unity-atoms#293]
**State your question below**
Can we change the access modifier from `private` to `protected` for a list variable in AtomValueList.cs file?
That change is small and can't break anything, I would also ask, can we make that change on the master branch to have this faster than V5 release.

**Add any additional information / background**
I'm trying to build upon AtomValueList my own classes to support few things like getting random items based on some conditions, etc. and I can't make it because the list access modifier is private so I don't have any access to the list.

**Comment by miikalo** [comment]
I don't see why this couldn't be in 4.4.4 as it's more like a loosened restriction rather than a "feature", so there can't be any code out there that would break because the previous access modified was "private".

**Comment by miikalo** [comment]
Released in 4.4.4.
