### ISSUE TITLE
[QUESTION] How do you instance an entire collection?

### ISSUE THREAD

**Issue by quezdk** [unity-atoms/unity-atoms#298]
**State your question below**
Is it possible to instance an entire collection of Atoms variables (including all the Atoms variables in the dictionary)? It doesn't seem to be the case and I'm struggling to find a way to send over multiple Atoms variables (in my cabled data transfer sim).

**Add any additional information / background**
I'm trying to create a simulation where objects that are physically connected can exchange data via a transmitter and receiver. I use Atoms collections to specify a data template, but the problem is, if I want to reuse the same collection (i.e. two similar devices sending data in the same format) I need to be able to make an instance of the entire collection.

**Comment by Kyrw** [comment]
First you want to instance the Atom Variables and Collections in runtime or in editor time? 
For editor time (like, just to automate the process), you can use unity methods to create the assets for you. (Its possible to do it in runtime, but its trickier.

You can load your collection using: `AssetDatabase.LoadAssetAtPath` and then add elements to it. Be aware of using AtomsVariables with collections, as internaly, the key is the value (string) of the StringVariable at the time it adds on the collection, not the atomvariable itself.  There is also a method to create objs with AssetDatabase.CreateAsset

I'm not a maintainer of the unity-atoms, but I suggest you reach the discord channel to discuss.

**Comment by ThimoDEV** [comment]
I think @Kyrw is quite a complete answer to the question above. @quezdk was your question answered in the discord as well or solved already?

**Comment by soraphis** [comment]
closed because of inactivity
