### ISSUE TITLE
[BUG] Errors when viewing atoms generated for non serializable types

### ISSUE THREAD

**Issue by IceTrooper** [unity-atoms/unity-atoms#303]
**Describe the bug**
Unity Atoms custom editors throw a NullReferenceException when custom generated type is not serializable. It's only the custom Editor windows/Drawers issue.

**To Reproduce**
For example:
1. Generate custom Atom for TimeSpan
2. Create TimeSpanVariable
3. Focus TimeSpanVariable
4. Many NullReferenceException errors appear in a console, because of the custom Inspector.
5. Similar errors are thrown when creating AtomReference or AtomVariable fields in custom scripts.

**Expected behavior**
Non-serializable types should work with UnityAtoms. Of course, we can't display values in the Editor because of the Unity serialization system, but... we should still be able to create and use those types of Atoms via code without any restrictions or making wrappers.

**Additional context**
https://discord.com/channels/640589221136171020/641007735525081116/893103547271487529
Copy-pasted from discord:
> You're right that I won't see any non-serializable type... and it's the desired effect. That's the case. I want to use AtomVariable/Events/etc. based on non-serialized type and I should not care about viewing those values in the Editor. I want to use it only for a scripting communication process, not for a designer. 
The problem is that UnityAtoms throws errors for non-serializable types when you focus on them. However, I think this should not be the case. Instead, it should just show things it can display like Developer Description, Id, Changed, etc. and not throwing errors.
In my case, I don't want to see the TimeSpan value in the Editor. I only want not to have errors in my console when I click on that Variable. The wrapper for TimeSpan is not the real solution in my opinion, because devs shouldn't be forced to make a wrapper if they don't care about viewing values in the editor in the first place. 
I can offer a pull request as I correct these errors. I want to have your opinion about it.

**Comment by AdamRamberg** [comment]
Fixed in #371
