### ISSUE TITLE
[BUG] FindByTag throws an exception

### ISSUE THREAD

**Issue by StupydHors** [unity-atoms/unity-atoms#305]
**Describe the bug**
FindByTag throws an exception if no more objects with that tag exist.

**To Reproduce**
1. Create a tag ("player") and add it to a singular object
2. Destroy that object
3. FindByTag throws an exception

**Expected behavior**
No exception should be thrown. A null value should be returned.

**Environment**
 - OS: N/A
 - Unity Version N/A
 - Version of Unity Atoms: 4.4.3
 - Version of Unity Atoms Tags: 4.4.3

**Additional context**
This happens even if a special component for handling the removal of all the tags with the OnDestroy callback is added.

I would suggest checking the size of the TaggedGameObjects static dictionary list of the particular key upon removal of a tag. And simply remove the entry if the remaining list is zero sized.

As of right now unnecessary TryCatch block is needed.

Even more problematic is that the entry won't ever get cleared.

A checkbox that enables the OnDestroy callback for the AtomTags component that removes all of the tags of this particular game object would be a welcome addition. Currently a special component is needed.

**Comment by soraphis** [comment]
as this merged and available with 4.4.4 , this can be closed
