### ISSUE TITLE
[BUG] Event replay buffer isn't fired in OnRegister and buffer does not clear.

### ISSUE THREAD

**Issue by mls-icaro** [unity-atoms/unity-atoms#324]
**Describe the bug**
Example: A void event is fired when the a listener object is disabled. When the listener object is enabled, I set in OnEnable button to listen the event (Register()). The void event at this moment has replayBuffer.count > 0. But the event is not fired in on Register.

I try check if replayBuffer.count > 0 and if it is, I can raise the event manually, but I would like clear the replayBuffer to the next time that I enable this listener gameobject , it doesn't fire again.

**Environment**
 - Unity Version [e.g. 2020.3]
 - Version of Unity Atoms [e.g. v4.4.3]

**Comment by mls-icaro** [comment]
I think the Register and Unregister method in AtomEvent<T> need a override
```
public **override** void Register(Action<T> action)
        {
            _onEvent += action;
            ReplayBufferToSubscriber(action);
        }
```

and the Register method in AtomEventBase need a virtual
`public **virtual** void Register(Action<T> action)`

**Comment by mls-icaro** [comment]
if we listen to the event using the Void Listener component, the callback is always called in OnEnable because the replay buffer is not cleared after the event is called.

**Comment by mls-icaro** [comment]
@AdamRamberg @miikalo

**Comment by mls-icaro** [comment]
I rewrote the cases to explain better. 

**Case A:** A event is fired by some game object G1.  In other game object G2 disabled there is a listener. When G2 is enabled, the replay buffer has size 1. The listener callback will be called. The proper behaviour. (When we use listener component)

But, after that, if the game object G2 is disabled and enabled, the listener callback will be called again even if there is no new event fired by game object G1. Is this the proper behaviour? 

**Case B:** Replay buffer is not used by game object G2 if the setup of listener is made by code in OnEnable. The Test Function is not executed, even if replay buffer size is bigger than 0. (This case works when we use listener component in G2)

    ```
public VoidEvent ListerEvent;

    private void OnEnable()
    {
        ListerEvent.Register(Test);
    }

    private void OnDisable()
    {
        ListerEvent.Unregister(Test);
    }

    public void Test()
    {
        Debug.Log("Event listened");
    }
```

**Comment by soraphis** [comment]
> But, after that, if the game object G2 is disabled and enabled, the listener callback will be called again even if there is no new event fired by game object G1. Is this the proper behaviour?

yes. the replay buffer is on the event. it has no memory which listener has listened to which event already.
the buffer is not cleared in that sense.


if you still feel that there is a bug, I'd ask for a unit test that shows the issue. thank you.
closed because of inactivity and (partial) invalidity.
reopen if needed
