### ISSUE TITLE
[BUG] Conditions can not be created

### ISSUE THREAD

**Issue by JuanObiJuan** [unity-atoms/unity-atoms#325]
Conditions can not be created

1. Go to Menu > Assets/Create/Unity Atoms/
2. There is no options to create conditions

**Screenshots**
![image](https://user-images.githubusercontent.com/1729541/152660070-d8523328-a60f-4aa9-b050-e0860fd2fb2f.png)

**Environment**
 - Windows
 - Unity Version 2020
 - Version of Unity Atoms 4.4.3

**Comment by theiviaxx** [comment]
Im hitting the same thing I think.  I created a simple bool condition

    public class NotBool : BoolCondition
    {
        public override bool Call(bool value)
        {
            return !value;
        }
    }

I Made an AtomGenerator, in there picked my name space and clicked re-generate and it created a condition in a `Generated` folder.  However the menu still doesn't show conditions to be made

**Comment by soraphis** [comment]
@theiviaxx you should really follow the documentation page I've linked.
remove the files the Generator created. A bool condition does not need to be generated, but you need to add the `[CreateAssetMenu(....)]` entry to it.

**Comment by theiviaxx** [comment]
@soraphis  oh duh, i didnt even see that line.  Yeah i probably just overcomplicated what i was trying to accomplish

Thanks!
