### ISSUE TITLE
[BUG] Compilation Error in StackTraceEntry prevents builds. requires AtomsPreferences

### ISSUE THREAD

**Issue by soraphis** [unity-atoms/unity-atoms#347]
**Describe the bug**

PR #329 made the projects unable to compile in builds:

as the lines require `AtomPreferences.IsDebugModeEnabled`
https://github.com/unity-atoms/unity-atoms/blob/v4.4.4/Packages/Core/Runtime/StackTrace/StackTraceEntry.cs#L63=

but due to conditional compilation: 
https://github.com/unity-atoms/unity-atoms/blob/v4.4.4/Packages/Core/Runtime/Preferences/AtomsPreferences.cs#L1=

this does not exist in builds

**Comment by AdamRamberg** [comment]
Closing since this has been merged to `canary` and will make the next release.
