### ISSUE TITLE
[BUG] Default changed and changedWithHistory events override custom events

### ISSUE THREAD

**Issue by boynukaline** [unity-atoms/unity-atoms#349]
**Describe the bug**
The fix for the problem when default changed and changedWithHistory events were not created introduced  the bug which overrides the current change event when a change event is added to a variable after running with empty change events.

**To Reproduce**

1.  Leave variable changed event blank and in runtime change variable value to something. Stop runtime.
2.  Add your change event to the variable, and go into runtime again and change variable value. Check variable event, it changes to default.

**Environment**
 - OS: [Windows 10]
 - Unity Version [2020.3.25f1]
 - Version of Unity Atoms [v4.4.4]

**Comment by soraphis** [comment]
#313 is the PR which introduced this bug

**Comment by AdamRamberg** [comment]
Fixed in #369
