### ISSUE TITLE
[QUESTION] How to install the input package via openupm?

### ISSUE THREAD

**Issue by matthiashermsen** [unity-atoms/unity-atoms#355]
**State your question below**
I wasn't able to find the install command for the input package in [the docs](https://unity-atoms.github.io/unity-atoms/introduction/installation#openupm). But you can find it in [the README](https://github.com/unity-atoms/unity-atoms#openupm).

Unfortunately when trying to install it via `openupm add com.unity-atoms.unity-atoms-input-system` I get the following error

> ERR! 404 package not found: com.unity-atoms.unity-atoms-input-system

**Add any additional information / background**
I think the install command for the input package should be added [here](https://github.com/unity-atoms/unity-atoms/blob/gh-pages/introduction/installation/index.html#L108)

Thanks in advance :)

**Comment by soraphis** [comment]
seems like the input-system package was not registered onto openupm 🤔

**Comment by matthiashermsen** [comment]
@soraphis thanks for your reply.

I solved it by adding the packages manually to the manifest file. But it would be awesome to have it on openupm :)

Am I correct that the docs ( mentioned in my question ) are lacking the single line for the package installation? I could add it if you want

**Comment by soraphis** [comment]
> 
@soraphis thanks for your reply.

I solved it by adding the packages manually to the manifest file. But it would be awesome to have it on openupm :)

> Am I correct that the docs ( mentioned in my question ) are lacking the single line for the package installation? I could add it if you want

well ... actually ... yes, but no. :D
since the package isn't yet on openupm it would be false for the docs to point towards it, as it is incorrect by the readme to point to it 😆 

but yeah. eventually, the docs should mention the package.

**Comment by matthiashermsen** [comment]
I personally would keep this issue as a reminder but feel free to close it :)

**Comment by KurtGokhan** [comment]
Can we upload it to OpenUPM? Is there anything we can help with?

**Comment by AdamRamberg** [comment]
Tried to upload it to OpenUPM, but wasn't allowed to create the PR. See screenshot below: 
![Skärmavbild 2022-10-23 kl  23 36 35](https://user-images.githubusercontent.com/10260896/197419492-9d100836-2cd0-4e37-81f6-96ede69c9362.png)

@favoyang I belive you uploaded all the rest of the packages. Do you have any clue on why the above happens? Would you mind adding the input system to OpenUPM?

**Comment by favoyang** [comment]
@AdamRamberg it's a glitch in the GitHub webpage. Try editing the filename field, then undo it. The "Propose new file" will be active.

![image](https://user-images.githubusercontent.com/125390/197434988-0b0d2107-08e2-4fe6-93fe-76c0339ad789.png)

**Comment by AdamRamberg** [comment]
Created a new PR towards OpenUPM that adds the Input System: https://github.com/openupm/openupm/pull/3491

**Comment by soraphis** [comment]
this is now merged and can be found:
https://openupm.com/packages/com.unity-atoms.unity-atoms-input-system/
