### ISSUE TITLE
[QUESTION] Is there a trigger hook to reference the gameobject itself instead of the other collider?

### ISSUE THREAD

**Issue by jtuchel** [unity-atoms/unity-atoms#356]
**State your question below**
Imagine having a collectable ( e.g. a coin ) with a collider. When the player moves into the trigger the coin might

- remove its collider
- play a sound
- raise an event to notify the score counter
- destroy itself

Without Unity Atoms I would create a Monobehaviour that handles all the logic inside `OnTriggerEnter`. With Unity Atoms I

- created a `Collected` event
- added a `ColliderEventInstancer` to the coin prefab and attached the event to it
- added a `OnTriggerHook` to the coin prefab and attached the `ColliderEventInstancer` to it
- added a `ColliderEventReferenceListener` to the coin prefab and attached the `ColliderEventInstancer` to it
- created a new custom Action `RemoveCollider` and added the action to the `ColliderEventReferenceListener`

Obviously my approach was wrong, the `Collider` is not the collider of the coin itself but the players one. But what I actually need is the coin itself.

Should I solve this "problem" by using the default Unity approach or is there something that provides me the following

> whenever something enters the trigger ( additional conditions ( e.g. player only ) might be added later ) execute some actions

Or maybe create a Monobehaviour and raise a custom event inside `OnTriggerEnter` by passing in the GameObject itself? 

And if that should be the case should I create my own hook ( if that's even possible ) similiar to the [OnTriggerHook](https://github.com/unity-atoms/unity-atoms/blob/master/Packages/MonoHooks/Runtime/Hooks/OnTriggerHook.cs) where I don't pass in the collider of the other GameObject but the current GameObject itself?

**Add any additional information / background**
I'm completely new to Unity Atoms :)

**Comment by soraphis** [comment]
> Should I solve this "problem" by using the default Unity approach or is there something that provides me the following

definitely: YES.

> raise an event to notify the score counter

this could be an atoms event, thus losing the coupling between coins and the counter UI, but all the other actions you mentioned are on the same gameobject, there is no point in trying to decouple things with the help of scriptable objects, sincere there is nothing to be decoupled.

Unity Atoms is a tool. the job of you as programmer is it, to know when to use which tool. You don't have to do "everything atom". 

> whenever something enters the trigger ( additional conditions ( e.g. player only ) 

if you make the collectables into one layer, that only collides with the player layer, you don't need this check, since you know from the beginning that collisions are only possible with the player layer for this object.
also the physics engine needs to do way less collision detection, too, when using physics layers.

> should I create my own hook ( if that's even possible ) 

it is absolutely possible! all the classes and base classes are public.

**Comment by jtuchel** [comment]
> it is absolutely possible! all the classes and base classes are public.

@soraphis I personally think a custom hook would be the "cleanest" solution :) What do you think about this one?

```cs
    [EditorIcon("atom-icon-delicate")]
    [AddComponentMenu("Unity Atoms/Hooks/On Trigger Passtrough Self Hook")]
    public sealed class OnTriggerPassthroughSelfHook : ColliderHook
    {
        [SerializeField]
        private Collider colliderToPassthrough;
        
        [SerializeField]
        private bool triggerOnEnter;
        
        [SerializeField]
        private bool triggerOnExit;
        
        [SerializeField]
        private bool triggerOnStay;

        private void OnTriggerEnter(Collider _)
        {
            if (triggerOnEnter)
            {
                OnHook(colliderToPassthrough);
            }
        }

        private void OnTriggerExit(Collider _)
        {
            if (triggerOnExit)
            {
                OnHook(colliderToPassthrough);
            }
        }

        private void OnTriggerStay(Collider _)
        {
            if (triggerOnStay)
            {
                OnHook(colliderToPassthrough);
            }
        }
    }
```
