### ISSUE TITLE
[BUG] On a enumVariable editor/drawer, Value is set by index and not by value

### ISSUE THREAD

**Issue by Kyrw** [unity-atoms/unity-atoms#363]
Create an enum, and generate an Atom from it.

Having a enum with values not starting in 0 (and not being contiguous) result on editor EnumVariable setting enum to invalid values, when changing it by the dropdown. This problem doesnt occurs if you use the debug mode of the Inspector. 

This occurs because AtomVariableEditor calls 
`var value = serializedObject.FindProperty("_value").GetPropertyValue();`

and this calls SerializedPropertyExtensions.GetPropertyValue
`case SerializedPropertyType.Enum: return property.enumValueIndex`

the correct behaviour (as far as I know) is to call
`case SerializedPropertyType.Enum: return property.intValue;`

as this returns the correct value of the enum (as an integer) and not its index on the enum array

**Comment by AdamRamberg** [comment]
Fixed in #364
