### ISSUE TITLE
[BUG] AtomBaseReferenceDrawer fails if the reference is in a List

### ISSUE THREAD

**Issue by lgarczyn** [unity-atoms/unity-atoms#391]
**Describe the bug**

When stored in a list, the reference drawer will exhibit strange behavior.

1. clicking on the kebab menu will open the menu normally, but on selection a drag-event will have been started on the list item. This drag event does not stop until a different object is selected in the inspector

![image](https://user-images.githubusercontent.com/17616347/218279664-f4c94a72-1434-419e-bfa4-d6b91e7e039b.png)

2. sometimes (probably due to the same effect) one of the references in the list becomes invisible

![image](https://user-images.githubusercontent.com/17616347/218279639-a524cae9-2700-49ea-8900-29eca881ece3.png)

3. sometimes while the object reference field is visible, clicking on it has no effect

All these problems last until a different object is selected. Folding the list field does not resolve it. Folding the behaviour inspector doesn't either.

**To Reproduce**

1. create a script with `[SerializeField] List<FloatReference> inputs;`
2. Open the script inspector in unity
3. Add a new list item 
7. Click ⁝
8. Move mouse

**Expected behavior**
Clicking on the kebab menu should just work

**Environment**
 - OS: Windows
 - Unity Version: 2022.2.4f1
 - Version of Unity Atoms: 4.4.5

**Comment by lgarczyn** [comment]
This appears to be due to a hotControl issue.

Unity Atoms should set a hotControl id when opening the popup, or use a different type of menu, such as a context menu maybe.

**Comment by soraphis** [comment]
Thanks for diving into the code on this one!

*tagging this issue, so I don't forget/overlook it anymore*

**Comment by lgarczyn** [comment]
Maybe it's been fixed, will try again when I have the time

**Comment by lgarczyn** [comment]
Confirmed fixed on 2022.2.21
