### ISSUE TITLE
[BUG] npm run generate:docs throws error

### ISSUE THREAD

**Issue by soraphis** [unity-atoms/unity-atoms#395]
Setting up the project as per https://github.com/unity-atoms/unity-atoms/blob/master/CONTRIBUTING.md#documentation is not possible.

Examples where removed from the repository and moved into their own repo: https://github.com/unity-atoms/unity-atoms-examples

also "just cloning" this example repo into an "Examples" folder is not sensible, because the examples repo contains a git submodule to the main repo.

the scripts/generateDocs.js should be fixed.

**Comment by soraphis** [comment]
digged a bit further into it, since this is kinda blocking the release process.

it seems that the new project architecture "prevents" the current generateDocs.js from working. as it is searching not only for examples but also for Library and other unity temporary folders. As it looks into the dlls and also tries to compile them.

I guess this is done to extract the API in the documentation page.
I'm not really sure how to fix it in the current project setup and I personally don't think it is actually worth it. I can't imagine anyone looking into the [API References](https://unity-atoms.github.io/unity-atoms/api/unityatoms) to search for something.
It does not feel organized, nor helpful. 

I guess people look into the documentation to find tutorials and guides. The API is something your IDE will tell you anyways.
Especially considering that many people use atoms to get away from code as much as possible.

**Comment by AdamRamberg** [comment]
I think there are at least 2 issues with `generateDocs.js`:
1) As you are mentioning, it expects a Unity project, so it actually should be moved to `unity-atoms-examples` repo. There are probably also tweaks to relative paths etc. that needs to be done. 
2) If I recall correctly there is an issue with the InputSystem package, which is needed to compile some of the docs and is expected not to be there for some. This would need to be fixed. 

All that being said, I believe you are right, it is not worth it to keep it. I vote for butchering it for the next release. We always have history so we have the possiblity to bring it back to life if we want to at a later stage.

**Comment by AdamRamberg** [comment]
The API docs has been removed. Closing
