### ISSUE TITLE
[BUG] Trying to create atoms for an interface creates flow of editor errors 

### ISSUE THREAD

**Issue by lgarczyn** [unity-atoms/unity-atoms#405]
**Describe the bug**
I tried generating atoms for a pretty simple interface, with a couple of useful methods. I want to inject this interface as a dependency into scripts.

While the scripts themselves compile fine, I get a flow of errors while editing the Variables, variable fields and reference fields.

**To Reproduce**

- Generate every atoms for an interface
- Watch the world burn

**Screenshots**

![image](https://github.com/unity-atoms/unity-atoms/assets/17616347/637e498c-a2f8-4f62-aa88-6f2ce6ee1d2f)
![image](https://github.com/unity-atoms/unity-atoms/assets/17616347/154e45cc-fb05-4bb2-9945-2f400e6ce2f2)
![image](https://github.com/unity-atoms/unity-atoms/assets/17616347/fa8cdb2c-4902-4122-8aa5-68d3aa971415)
![image](https://github.com/unity-atoms/unity-atoms/assets/17616347/635cfc4a-2adc-43c0-92ba-75405b77fcc0)
(on the image above, it looks like its also breaking the editors of the sibling scripts)
![image](https://github.com/unity-atoms/unity-atoms/assets/17616347/ba244790-f94a-4e11-9f3c-a6d33b60e464)

`NullReferenceException: Object reference not set to an instance of an object
UnityAtoms.Editor.VariableDrawer`1[T].OnGUI (UnityEngine.Rect position, UnityEditor.SerializedProperty property, UnityEngine.GUIContent label) (at ./Library/PackageCache/com.unity-atoms.unity-atoms-core@4.4.5/Editor/Drawers/VariableDrawer.cs:22)
UnityEditor.PropertyDrawer.OnGUISafe (UnityEngine.Rect position, UnityEditor.SerializedProperty property, UnityEngine.GUIContent label) (at <582c35e8f45345d395e99f8e72e3c16d>:0)
UnityEditor.PropertyHandler.OnGUI (UnityEngine.Rect position, UnityEditor.SerializedProperty property, UnityEngine.GUIContent label, System.Boolean includeChildren, UnityEngine.Rect visibleArea) (at <582c35e8f45345d395e99f8e72e3c16d>:0)
UnityEditor.PropertyHandler.OnGUI (UnityEngine.Rect position, UnityEditor.SerializedProperty property, UnityEngine.GUIContent label, System.Boolean includeChildren) (at <582c35e8f45345d395e99f8e72e3c16d>:0)
UnityEditor.PropertyHandler.OnGUILayout (UnityEditor.SerializedProperty property, UnityEngine.GUIContent label, System.Boolean includeChildren, UnityEngine.GUILayoutOption[] options) (at <582c35e8f45345d395e99f8e72e3c16d>:0)
UnityEditor.EditorGUILayout.PropertyField (UnityEditor.SerializedProperty property, UnityEngine.GUIContent label, System.Boolean includeChildren, UnityEngine.GUILayoutOption[] options) (at <582c35e8f45345d395e99f8e72e3c16d>:0)
UnityEditor.EditorGUILayout.PropertyField (UnityEditor.SerializedProperty property, System.Boolean includeChildren, UnityEngine.GUILayoutOption[] options) (at <582c35e8f45345d395e99f8e72e3c16d>:0)
UnityEditor.UIElements.PropertyField.<CreatePropertyIMGUIContainer>b__43_0 () (at <582c35e8f45345d395e99f8e72e3c16d>:0)
UnityEngine.UIElements.IMGUIContainer.DoOnGUI (UnityEngine.Event evt, UnityEngine.Matrix4x4 parentTransform, UnityEngine.Rect clippingRect, System.Boolean isComputingLayout, UnityEngine.Rect layoutSize, System.Action onGUIHandler, System.Boolean canAffectFocus) (at <d293f45b4ec64e6c9e762fe89794e7a5>:0)
UnityEngine.UIElements.IMGUIContainer.HandleIMGUIEvent (UnityEngine.Event e, UnityEngine.Matrix4x4 worldTransform, UnityEngine.Rect clippingRect, System.Action onGUIHandler, System.Boolean canAffectFocus) (at <d293f45b4ec64e6c9e762fe89794e7a5>:0)
UnityEngine.UIElements.IMGUIContainer.DoIMGUIRepaint () (at <d293f45b4ec64e6c9e762fe89794e7a5>:0)
UnityEngine.UIElements.UIR.RenderChainCommand.ExecuteNonDrawMesh (UnityEngine.UIElements.UIR.DrawParams drawParams, System.Single pixelsPerPoint, System.Exception& immediateException) (at <d293f45b4ec64e6c9e762fe89794e7a5>:0)
Rethrow as ImmediateModeException
UnityEngine.UIElements.UIR.RenderChain.Render () (at <d293f45b4ec64e6c9e762fe89794e7a5>:0)
UnityEngine.UIElements.UIRRepaintUpdater.Update () (at <d293f45b4ec64e6c9e762fe89794e7a5>:0)
UnityEngine.UIElements.VisualTreeUpdater.UpdateVisualTreePhase (UnityEngine.UIElements.VisualTreeUpdatePhase phase) (at <d293f45b4ec64e6c9e762fe89794e7a5>:0)
UnityEngine.UIElements.Panel.UpdateForRepaint () (at <d293f45b4ec64e6c9e762fe89794e7a5>:0)
UnityEngine.UIElements.Panel.Repaint (UnityEngine.Event e) (at <d293f45b4ec64e6c9e762fe89794e7a5>:0)
UnityEngine.UIElements.UIElementsUtility.DoDispatch (UnityEngine.UIElements.BaseVisualElementPanel panel) (at <d293f45b4ec64e6c9e762fe89794e7a5>:0)
UnityEngine.UIElements.UIElementsUtility.UnityEngine.UIElements.IUIElementsUtility.ProcessEvent (System.Int32 instanceID, System.IntPtr nativeEventPtr, System.Boolean& eventHandled) (at <d293f45b4ec64e6c9e762fe89794e7a5>:0)
UnityEngine.UIElements.UIEventRegistration.ProcessEvent (System.Int32 instanceID, System.IntPtr nativeEventPtr) (at <d293f45b4ec64e6c9e762fe89794e7a5>:0)
UnityEngine.UIElements.UIEventRegistration+<>c.<.cctor>b__1_2 (System.Int32 i, System.IntPtr ptr) (at <d293f45b4ec64e6c9e762fe89794e7a5>:0)
UnityEngine.GUIUtility.ProcessEvent (System.Int32 instanceID, System.IntPtr nativeEventPtr, System.Boolean& result) (at <e35f2ca690d241b7981de4b44e6c2240>:0)

`

**Environment**
 - Unity Version [e.g. 2019.3]
 - Version of Unity Atoms [e.g. v2.0.0]

**Additional context**

**Comment by soraphis** [comment]
as unity is not able to serialzie interfaces, untiy atoms also is not.

what is your exected result?

**Comment by lgarczyn** [comment]
> as unity is not able to serialzie interfaces, unity atoms also is not.
> 
> what is your exected result?

Not crashing and burning ideally. If interfaces are not supported, the templates should mention "where T is class".

If they are supported for some types (plain events or interfaces on UnityEngine.Object), it should be mentioned somewhere.

**Comment by soraphis** [comment]
Well, You can create an atom class for interfaces. You should be able to use them from code just fine.

Issue is with the editor...

Maybe i will find some time to make it less spamy...

**Comment by lgarczyn** [comment]
> Well, You can create an atom class for interfaces. You should be able to use them from code just fine.
> 
> Issue is with the editor...
> 
> Maybe i will find some time to make it less spamy...
> 
> Btw: it's not crashing, is it? Not sure what you mean by burning, but it's only spamming because unity calls the editor drawer that often. 

Just a warning label field instead of an object field would be nice, in the reference and variable editor.

**Comment by soraphis** [comment]
looked into reproducing it, and at least in 4.4.6 I can't.

I generated the Variable atom for an interface and added it as a variable to a script. besides not rendering, everything seems to work fine 

![image](https://github.com/unity-atoms/unity-atoms/assets/3066582/d59b6ecd-21c4-4f65-825d-788b47ee0b6a)
![image](https://github.com/unity-atoms/unity-atoms/assets/3066582/a5fba85b-6bc5-43f0-91ed-14830a961833)

so, please updating to 4.4.6 should solve this, if not feel free to re-open
