### ISSUE TITLE
[Documentation] Add section about Pre Change Transformers

### ISSUE THREAD

**Issue by soraphis** [unity-atoms/unity-atoms#410]
The current documentation does not mention or explain the usage of "Pre Change Transformers"

**Comment by AdamRamberg** [comment]
There is a section about it [here](https://unity-atoms.github.io/unity-atoms/introduction/overview#pre-change-transformers). Do you expect it to be somewhere else?

**Comment by soraphis** [comment]
Splitting "Overview and Philosophy" into "Philosophy" and "Overview"
Where overview gives an overview over all featuers.
Also there should be a dedicated tutorial section about transformers, maybe as a sub-page of Variables.

**Comment by AdamRamberg** [comment]
That makes sense 👍

**Comment by AdamRamberg** [comment]
Added to the v4.4.6 release

**Comment by AdamRamberg** [comment]
Fixed in #413
