### ISSUE TITLE
[BUG] NullReferenceException in HandlePlayModeStateChange

### ISSUE THREAD

**Issue by burakomer** [unity-atoms/unity-atoms#417]
**Describe the bug**
When exiting or entering the Play mode, sometimes there are null references left in the `_instances` static list of atom variables inside the AtomVariable generic class. This leads to NullReferenceException when iterating this list on `HandlePlayModeStateChange` method

**To Reproduce**
I don't know when it happens.

**Expected behavior**
No exceptions

**Screenshots**
I don't have any right now.

**Environment**
 - OS: macOS Editor
 - Unity Version 2021.3.21f1
 - Version of Unity Atoms v4.4.5

**Additional context**
Nothing

**Comment by AdamRamberg** [comment]
Fixed in #421
