### ISSUE TITLE
[BUG] AtomValueList keeps runtime modifications

### ISSUE THREAD

**Issue by soraphis** [unity-atoms/unity-atoms#418]
**Describe the bug**
Since AtomValueLists don't have an "initial" field (like variables have), they will keep runtime modifications after exiting playmode in the editor. 

(obviously "start cleared" does not suffer this issue (with enabled domain reload, for disabled see #419))

**Environment**
 - Unity Version [e.g. 2019.3]
 - Version of Unity Atoms [4.4.6]

**Comment by AdamRamberg** [comment]
Fixed in #420
