### ISSUE TITLE
[BUG] FiniteStateMachine not firing events anymore

### ISSUE THREAD

**Issue by lgarczyn** [unity-atoms/unity-atoms#424]
**Describe the bug**
I'm using a FiniteStateMachine, and multiple script subscribe to the Changed event

since updating from 4.4.5 to 4.4.6, the Changed event doesn't seem to fire, yet checking for change on Update works perfectly

Raising the Changed event from the editor somehow still doesn't trigger any listener

**Comment by soraphis** [comment]
will probably be fixed by this line:

https://github.com/unity-atoms/unity-atoms/pull/420/files#diff-f264504757f7204f9f080e589a2409ab605ddca0a9dfc7bf2a0bffb1c6aca156L73

**Comment by AdamRamberg** [comment]
Fixed in #420
