### ISSUE TITLE
[QUESTION] Subpackages documentation

### ISSUE THREAD

**Issue by quentinleguennec** [unity-atoms/unity-atoms#429]
Hi, I'm new to Unity Atoms and I can see there is a list of subpackages available, but I have no idea what these do, and could not find any documentation. 
How can I tell what features these subpackages add, is there documentation somewhere?
Thanks!

**Comment by soraphis** [comment]
**Core** is the main package. you NEED this, if you want to use atoms.

[**Base Atoms**](https://unity-atoms.github.io/unity-atoms/subpackages/base-atoms) is a set of standard components, like in the core package you have an abstract class AtomsVariable, and in the BaseAtoms you have all the common datatypes like IntVariable, FloatVariable, StringVariable, ...

you usually WANT this, if you wanna use atoms.

[**FSM**](https://unity-atoms.github.io/unity-atoms/subpackages/fsm) - Finite State machine.
If you need an FSM, based on atoms, this is ready to go.

**[Input System](https://unity-atoms.github.io/unity-atoms/subpackages/input-system)** - there is a video about this, but I personally find this package pretty situational.

[**MonoHooks**](https://unity-atoms.github.io/unity-atoms/subpackages/mono-hooks) Is similar to BaseAtoms, it contains a set of predefined assets which may alleviate writing some components yourself.

**[Tags](https://unity-atoms.github.io/unity-atoms/subpackages/tags)** is for people that like the unity tags to find or filter gameobjects. Objects can have multiple tags and there are  nearly no garbage allocations.

there are more packages, and the documentation for them is mostly a stub. My recommendation would be to just take a glimpse here in github into the package content, as the packages are usually not that large anyways.

**Comment by quentinleguennec** [comment]
Thanks a lot! I'll look into the packages content for the others. I was wondering about the mobile one in particular since I want to build a mobile app. I'll mark this as resolved.
