### ISSUE TITLE
[BUG] StackTraces allocate garbage when DebugMode = false

### ISSUE THREAD

**Issue by soraphis** [unity-atoms/unity-atoms#434]
Was digging around because of this post: https://www.reddit.com/r/Unity3D/comments/177zvk5/unity_atoms_performance_is_horrible_but_it_doesnt/

and found that for simple integers / floats the following call boxes "item": 

https://github.com/unity-atoms/unity-atoms/blob/master/Packages/Core/Runtime/Events/AtomEvent.cs#L104

Also the Get() implementation of the DebugMode flag always looks up the value from the EditorPrefs

https://github.com/unity-atoms/unity-atoms/blob/master/Packages/Core/Runtime/Preferences/AtomsPreferences.cs#L27

**Comment by AdamRamberg** [comment]
Great fidings! Fixed in #436
