### ISSUE TITLE
[FEATURE] Set event name suggestion on Variable Changed event creation

### ISSUE THREAD

**Issue by mutmedia** [unity-atoms/unity-atoms#67]
Is would be really nice to have an automatically set up name for the event when creating a new event for a variable (could be fancy and try to understand what naming convention is being used or just force some naming convention such as appending " changed" or "_changed", or some middle ground such as a setting regex for it?)

This makes the process of creating new events for variables less repetitive (especially in the case mentioned in #66 )

**Comment by AdamRamberg** [comment]
Great idea! I think that just adding the postfix "Changed" to the Event as the default name will suffice for now or what do you think @mutmedia? The tricky part implementing this would be to get the parent of of the `SerializedProperty` in the `AtomDrawer`. You would then use the name of the parent Atom (if there is one) + the name of the property of the Atom you are creating. Eg: if you have a Variable called `MyVariable` and you click Create for the `Changed` event of that Variable the default name would be `MyVariableChanged`.

**Comment by soraphis** [comment]
(untested):
in the event drawer, you can get property.serializedObject.Name which should yield the Scripts's name or the scriptableObjects's asset name.

and of course you could get the property.Name to get the variable name itself.

_________________________________

**scenario 1**: you're in an `IntVariable` AtomVariable named "fooBar" you click "create" for the "changed" event of type IntEvent.

** scenario 2*: you're on an GameObject Player in a Script named Health you click "create" for the "reachedZero" event of type BoolEvent.

| pattern | scenario 1 | scenario 2 |
| <parent>On<Event> | IntVariableOnChanged | HealthOnReachedZero |
| <parent>Changed  | IntVariableChanged | HealthChanged |
| <object name>Changed  | fooBarChanged | PlayerChanged |
| <object name><parent>Changed  | IntVariablefooBarChanged | PlayerHealthChanged |
| <object name><parent>On<Event>  | IntVariablefooBarOnChanged | PlayerHealthOnReachedZero |

**Comment by AdamRamberg** [comment]
I think pattern 3 (row 3) works best for **scenario 1**, however it isn't great for scenario 2. Maybe we could via reflection see if the parent is an Atom Variable or not? If it is we use the `<object name>Changed` pattern, otherwise we just default to `AtomEvent` or maybe `<property name>`?

**Comment by AdamRamberg** [comment]
Fixed in #317
